<a href="https://colab.research.google.com/github/arshi246/Numpy/blob/main/Numpy_Concept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Arshi

Roll_No : 874718

Numpy




NumPy Core Operations

NumPy stands for Numerical Python.
It is a Python library used for working with numbers, arrays, and mathematical calculations.
NumPy is very useful in:
Data Science
Machine Learning
Data Analysis
Artificial Intelligence
The main benefit of NumPy is that it can perform calculations on a large amount of numerical data very easily.

## 1. Import NumPy

First, we need to import NumPy.

```python
import numpy as np
```

`np` is just a short name for NumPy.

After importing it, we can use NumPy functions like this:

```python
np.array()
np.mean()
np.max()
```

# 2. Python List vs NumPy Array

A normal Python list looks like this:

In [ ]:
marks = [70, 80, 90, 60]

A NumPy array looks like this:

In [ ]:
import numpy as np

In [ ]:
import numpy as np

marks = np.array([70, 80, 90, 60])

print(marks)

[70 80 90 60]


Both can store data, but NumPy arrays are better for numerical calculations. NumPy adds 5 to every value automatically.

For example:

In [ ]:
marks = np.array([70, 80, 90])
print(marks + 5)


[75 85 95]


# 3. Creating NumPy Arrays

## One-Dimensional Array

This is called a 1D array.

In [ ]:
numbers = np.array([10, 20, 30, 40])

print(numbers)

[10 20 30 40]


Two-Dimensional Array

We can imagine this data as student marks.

```
        Math   English   Science

Ali      70       80       90
Sara     60       75       85
Ahmed    88       92       95
```

Rows can represent students.

Columns can represent subjects.

In [ ]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95]
])

print(marks)

[[70 80 90]
 [60 75 85]
 [88 92 95]]


# 4. Important Array Properties

Suppose we have this array:

In [ ]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

## ndim

`ndim` tells us how many dimensions the array has.

In [ ]:
print(f"Dimesion Count : {data.ndim}")

Dimesion Count : 2


## shape

`shape` tells us the number of rows and columns.



This means:

```
2 rows
3 columns
```

In [ ]:
print(f"Shape : {data.shape}")

Shape : (2, 3)


## size

`size` tells us the total number of values.

In [ ]:
print(f"Size : {data.size}")

Size : 6


## dtype

`dtype` tells us the data type.

In [ ]:
print(f"Data Type : {data.dtype}")

Data Type : int64


# 5. Indexing

Indexing means getting one specific value from an array.

Indexing starts from `0`.

In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])

10


In [ ]:
print(numbers[1])

20


In [ ]:
print(numbers[2])

30


In [ ]:
print(numbers[3])

40


In [ ]:
print(numbers[4])

50


## Negative Indexing

To get the last value:

In [ ]:
print(numbers[-1])

50


In [ ]:
print(numbers[-2])

40


In [ ]:
print(numbers[-3])

30


In [ ]:
print(numbers[-4])

20


In [ ]:
print(numbers[-5])

10


6. Indexing in a 2D Array

In [ ]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])

To get 80:

In [ ]:
print(marks[0,1])

80


The pattern is:

```
array[row, column]
```

So:

```
marks[0, 1]
```

means:

```
Row 0
Column 1
```

# 7. Slicing

Slicing means getting multiple values from an array.

The pattern is:

```
[start : stop]
```

The start value is included.

The stop value is not included.

In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

In [ ]:
print(numbers[0 : 5])

[10 20 30 40 50]


In [ ]:
print(numbers[1:4])

[20 30 40]


# 8. Vectorized Operations

This is one of the most important features of NumPy.

NumPy can perform one operation on all values at the same time.

In [ ]:
numbers = np.array([10, 20, 30, 40])

Add:

In [ ]:
print(numbers + 5)

[15 25 35 45]


Subtract:

In [ ]:
print(numbers - 5)

[ 5 15 25 35]


Multiply:

In [ ]:
print(numbers * 5)

[ 50 100 150 200]


Divide:

In [ ]:
print(numbers / 5)

[2. 4. 6. 8.]


This is called a **vectorized operation**.

We do not need to use a loop for every value.

Agar har operation ko numbers mein store karwao
Har line ke baad numbers update hota rahega:
Toh end mein numbers ki value last operation ka result hogi.

In [ ]:
numbers = np.array([10, 20, 30, 40])

numbers = numbers + 5
numbers = numbers - 2
numbers = numbers * 3
numbers = numbers / 2

print(numbers)

[19.5 34.5 49.5 64.5]


Specific value ko change karna ho tw :

In [ ]:
numbers = np.array([10, 20, 30, 40])
numbers[1] = 100
print(numbers)

[ 10 100  30  40]


Specific value me calculation karni ho tw :


Calculate + specific index mein store → original array updated
Yani = sabse important cheez hai. = ke left side par jo jagah hoti hai, result wahan store hota hai.

In [ ]:
numbers[2] = numbers[2] + 5
print(numbers)

[ 10 100  35  40]


or agar ham variable me store nh karwayengay tw wo original cahnge nahi karega

In [ ]:
numbers = np.array([10, 20, 30, 40])

numbers[1] * 2

print(numbers)

[10 20 30 40]



9. Operations Between Two Arrays
We can also perform operations between two arrays.



# Addition:

It works like this:

```
10 + 1 = 11
20 + 2 = 22
30 + 3 = 33
```

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1,2,3])

print(a+b)

[11 22 33]



Multiplication:


It works like this:

```
10 × 1
20 × 2
30 × 3
```

This is called an **element-wise operation**.

In [ ]:
print(a*b)

[10 40 90]


# 10. Mathematical Functions

NumPy already has many useful mathematical functions.

Square Root



In [ ]:
numbers = np.array([4, 9, 16, 25])


Agar original change krni ho tw variable me store karwayengay direct print nahi :

In [ ]:
numbers = np.sqrt(numbers)
print(numbers)

[2. 3. 4. 5.]


Power

In [ ]:
numbers = np.array([2, 3, 4])
print(np.power(numbers,2))
print(numbers)


[ 4  9 16]
[2 3 4]


Absolute Value

In [ ]:
numbers = np.array([-10, -5, 4, 8])
print(np.abs(numbers))

[10  5  4  8]


Round

In [ ]:
numbers = np.array([4.2, 5.7, 8.9])
print(np.round(numbers))

[4. 6. 9.]


11. Aggregation Functions
Aggregation functions give us summary values.

Example:

In [ ]:
marks = np.array([70, 85, 60, 95, 80])

Sum

In [ ]:
print(np.sum(marks))

390


Average

In [ ]:
print(np.mean(marks))

78.0


Maximum Value

In [ ]:
print(np.max(marks))

95


Minimum Value

In [ ]:
print(np.min(marks))

60


Median

In [ ]:
print(np.median(marks))

80.0


Standard Deviation







Standard deviation tells us how spread out the values are.

In [ ]:
print(np.std(marks))

12.083045973594572


12. Conditions in NumPy
We can apply conditions directly to NumPy arrays.

NumPy checks every value.

For example:

```
30 >= 50 → False
50 >= 50 → True
80 >= 50 → True
```

In [ ]:
marks = np.array([30, 50, 80, 45, 90, 20])
print(marks >=50)

[False  True  True False  True False]


13. Filtering Data

Filtering is very useful in data analysis.
We can also get only the values that match a condition.

Example:

In [ ]:
marks = np.array([30, 50, 80, 45, 90, 20])
passed = marks[marks>50]
print(passed)

[80 90]


In [ ]:
print(f"Total Passed Students : {len(passed)}")

Total Passed Students : 2


To get failed marks:

In [ ]:
failed = marks[marks<=50]
print(failed)

[30 50 45 20]


In [ ]:
print(f"Total Failed Students : {len(failed)}")

Total Failed Students : 4


# 14. Reshape

Important rule:

The total number of values must stay the same.

```
2 × 3 = 6
```

So the reshape is possible.

`reshape()` changes the structure of an array.

Example:

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6])
print(numbers)

[1 2 3 4 5 6]


Now convert it into 2 rows and 3 columns:

In [ ]:
new_array = numbers.reshape(2,3)
print(new_array )

[[1 2 3]
 [4 5 6]]


# 15. Flatten

`flatten()` changes a multi-dimensional array into a one-dimensional array.

In [ ]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(data.flatten())

[1 2 3 4 5 6]


16. Useful NumPy Functions

## zeros()

Creates an array with zero values.

In [ ]:
var = np.zeros(5)
print(var)

[0. 0. 0. 0. 0.]


## ones()

Creates an array with one values.

In [ ]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


arange()

Creates a range of numbers.

In [ ]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


Using a step:

In [ ]:
print(np.arange(0, 11, 2))

[ 0  2  4  6  8 10]


# 17. Random Numbers

NumPy can also generate random numbers.

The output can be different every time.

This is useful for testing and practice.

In [ ]:
marks = np.random.randint(40, 100, 10)
print(marks)

[63 86 64 87 84 73 67 86 48 49]


# Class Practice: Student Marks Analyzer

Now we will use different NumPy concepts in one small program.

## Problem

We have marks of different students.

We want to find:

- Average marks
- Highest marks
- Lowest marks
- Total passed students
- Total failed students

In [ ]:
marks = np.array([45, 78, 90, 32, 67, 88, 55, 40, 95, 28])

print("Student Marks:")
print(marks)

# Average Marks
print(f"\nAverage Marks : {np.mean(marks)}")

# Highest marks
print(f"Highest Marks : {np.max(marks)}")

# Lowest marks
print(f"Lowest Marks : {np.min(marks)}")

passed = marks[marks>=50]
failed = marks[marks<50]


print(f"\nPassed Students Marks : {passed}")
print(f"\nFailed Students Marks : {failed}")

# Total passed students
print(f"Total passed students : {len(passed)}")


# Total failed students
print(f"Total Failed students : {len(failed)}")

Student Marks:
[45 78 90 32 67 88 55 40 95 28]

Average Marks : 61.8
Highest Marks : 95
Lowest Marks : 28

Passed Students Marks : [78 90 67 88 55 95]

Failed Students Marks : [45 32 40 28]
Total passed students : 6
Total Failed students : 4


# Student Practice Tasks

## Task 1

Create this array:

```
10, 20, 30, 40, 50
```

Find:

- Sum
- Average
- Maximum
- Minimum

In [ ]:
marks = np.array([10, 20, 30, 40, 50])

# Sum
print(f"Sum : {np.sum(marks)}")

# Average
print(f"Average : {np.mean(marks)}")

# Maximum
print(f"Maximum : {np.max(marks)}")

# Minimum
print(f"Minimum : {np.min(marks)}")


Sum : 150
Average : 30.0
Maximum : 50
Minimum : 10


## Task 2

Create this array:

```
45, 80, 30, 90, 55, 20
```

Display only the values greater than or equal to `50`.

In [ ]:
marks = np.array([45, 80, 30, 90, 55, 20])
print(marks[marks>=50])

[80 90 55]


## Task 3

Create this array:

```
1, 2, 3, 4, 5, 6
```

Change it into:
2 rows
3 columns

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6])
print(numbers.reshape(2,3))

[[1 2 3]
 [4 5 6]]


## Task 4

Generate `10` random marks between `40` and `100`.

Then find:

- Average
- Highest marks
- Lowest marks

In [ ]:
numbers = np.random.randint(40,100,10)
print(numbers)

# Average
print(f"\nAverage : {np.mean(numbers)}")

# Highest marks
print(f"Highest Marks : {np.max(numbers)}")

# Lowest marks
print(f"Lowest Marks : {np.min(numbers)}")


[73 97 87 89 87 91 61 78 75 53]

Average : 79.1
Highest Marks : 97
Lowest Marks : 53


## Task 5

Create this marks array:

```
35, 67, 89, 45, 90, 22, 70, 58
```

Passing marks are `50`.

Find:

- Passed marks
- Failed marks
- Number of passed students
- Number of failed students

In [ ]:
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = marks[marks>=50]
failed = marks[marks<50]

print(f"Passed Marks : {passed}")
print(f"Failed Marks : {failed}")

# Number of passed students
print(f"\nNumber of passed students : {len(passed)}")

# Number of failed students
print(f"Number of failed students : {len(failed)}")

Passed Marks : [67 89 90 70 58]
Failed Marks : [35 45 22]

Number of passed students : 5
Number of failed students : 3


# Quick Revision

After this topic, you should understand:

- What NumPy is
- How to create NumPy arrays
- 1D and 2D arrays
- `ndim`
- `shape`
- `size`
- `dtype`
- Indexing
- Slicing
- Vectorized operations
- Mathematical functions
- Sum, mean, min, and max
- Conditions
- Filtering
- Reshape
- Flatten
- Random numbers
# Main Idea

NumPy is not only used to create arrays.

It helps us store and process numerical data easily and efficiently.
Data
  ↓
NumPy Array
  ↓
Operations
  ↓
Filtering
  ↓
Calculations
  ↓
Data Analysis
These NumPy concepts will also help us later when we start working with Pandas, Data Analysis, and Machine Learning.